HW01
usoltsev37/hse-homework-sd pull request #1
Opened 2022-01-22 14:53 UTC by Readrid

Выполнили: 
[Илья Смирнов](@smirok) 
[Владимир Федоров](@Readrid)
[Никита Усольцев](@usoltsev37)

2022-01-22 15:52 UTC, yurii-litvinov requested changes
Очень неподробно. Даже если пробежаться по требованиям из условия:
- одинарные и двойные кавычки не упоминаются нигде
- окружение упоминается только в "В начале парсинга производится подстановка соответсвующих переменных из окружения". Это лучше, чем ничего, но как переменные окружения выставлять, как они парсятся, как связаны с внешними процессами? Мапа со значениями переменных окружения у каждой команды присваивания своя, судя по диаграмме, это ок?
- поддержка пайпов у вас задекларирована, но без каких-либо подробностей

Также, над чем бы ещё стоило подумать:
- exit кажется интересной командой в том плане, что оказывает влияние на поток управления. У вас она просто есть
- у вас написано, что парсер создаёт команды — но как, и не будет ли он слишком умным? Кажется, ему и так достался самый сложный кусок работы.
- про потоки в пайплайне просили подумать в презентации — может, вы подумали, но в документации не написали

По форме ещё пара мелких замечаний:
- судя по диаграмме лексер принимает список токенов, не возвращает?
- по диаграмме не очевидно, что парсер вообще как-то связан с командами
- execute() у команды ничего не возвращает, это странно
- компонентность на диаграмме никак не отражена. Можно было каждый компонент прямоугольником обвести, например (ну или раз у вас почти диаграмма классов, символом компонента). А потом и в коде надо будет такой же структуры придерживаться.

В целом начало хорошее, но требует уточнения. Представьте, что я дам это описание, не знаю, второму курсу на реализацию в следующем году, как одну из первых домашек по Java. Надо, чтобы было прямо вообще понятно, что кодить.

Пока 4 балла из 10.

2022-01-22 15:52 UTC, yurii-litvinov commented on hw01/README.md
> +* **Парсер.** Состоит из лексера, парсера и соответствующих лексемам токенов. В начале парсинга производится подстановка соответсвующих переменных из окружения. Далее с помощью полученного синтаксиче
Это хотелось бы раз в пять подробнее. Например, `производится подстановка соответсвующих переменных из окружения` — а как? В зависимости от стратегии подстановки могут получаться совершенно разные результаты, как обсуждалось на паре (подстановка пока можно, подстановка один раз, примеры типа `x=$x`). И при реализации надо будет думать, _как_ парсить, _как_ подставлять (всякие там кавычки — будет это просто проход по строке регэкспами, автомат, грамматика, что-то ещё). А архитектура как раз и нужна для того, чтобы при реализации думать было не нужно.

2022-01-22 15:52 UTC, yurii-litvinov commented on hw01/README.md
> +* **Команды**. Каждая команда в CLI -- это отдельный класс, который наследуется от ```AbstractCommand```. Чтобы добавить новую команду необходимо просто отнаследоваться от ```AbstractCommand``` и реа
Раз пайплайн — тоже команда, надо где-нибудь описать, как он работает, потому что тут это довольно критично. В вашем описании буквально ничего про потоки ввода-вывода, например.

2022-01-30 16:13 UTC, yurii-litvinov requested changes

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +Наше приложение состоит из трех основных компонент: **Parser**, **Controller** и **Command Executor**. **Parser** отвечает за обработку пришедшей строки, на выход выдает некое представление `Expressi
Стоило явно обозначить их на диаграмме, подписав соответствующие прямоугольники. А то даже и непонятно, Parser и Command Executor вроде можно найти, а Controller вообще нету.

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  * Назовем кавычки внешними, если они не содержатся внутри других кавычек. Идем по каждому символу строки. Если встретили знак `$` и при этом мы **не** находимся внутри внешних одинарных кавычек, то
Я бы ещё символ пайплайна считал концом имени

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +* `Lexer`. Представляет интерфейс обычного лексера с единственным методом `getNextToken()`. Конкретно в нашей реализации имеет имплементацию `LexerImpl`, которая разбивает текст на токены из `Token`.
Судя по диаграмме лексер использует парсер. Не наоборот?

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  Expression := (Command pipe Expr)* Command
```suggestion
  Expression := (Command pipe Expression)* Command
```
?
Но что-то странное получилось :)

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  Command := (String space Args?) | Assignment
После команды обязателен пробел? `pwd|echo 1` не распарсится, и казалось бы, без всякой видимой причины. Но, конечно, ваш шелл --- ваши правила. Единственное, что стоит явно пояснить, что оно вот так, и это лучше/не сильно хуже, чем у остальных, потому что... (например, грамматика проще). Хотя пробелы при парсинге обычно просто игнорируются --- они для лексера в основном.

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  * `Expression`: список `Command`. В случае одной команды состоит всего из одного аргумента, в случае пайплайна -- из нескольких.
На диаграмме оно `Expr`, и ни `Command`, ни `Expr` на диаграмме не нарисованы, нехорошо (какая-то внутренняя неконсистентность).

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +* `Parser`. Интерфейс парсера. Стандартная имплементация(`ParserImpl`) принимает в конструкторе строку, которая в дальнешем парсится в методе `parse()`. `Parser` использует `Lexer`, постепенно получа
```suggestion
* `Parser`. Интерфейс парсера. Стандартная имплементация(`ParserImpl`) принимает в конструкторе строку, которая в дальнешем парсится в методе `parse()`. `Parser` использует `Lexer`, постепенно получая из него новые токены, которые обрабатываются при помощи соответствующей грамматики. Попутно строится объект `Expression`, который возвращается в результате метода `parse()`.

```

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  * `AbstractCommand`. Каждая команда в CLI -- это отдельный класс, который наследуется от него. Чтобы добавить новую команду необходимо просто отнаследоваться от AbstractCommand и реализовать метод
А аргументы? IOEnvironment --- это только потоки, как я понял. А из того, что у вас команды лежат в CommandStorage и, как я понял, один экземпляр команды переиспользуется для всех вхождений команды в пайплайн (что вполне хорошо), нельзя передавать аргументы в конструктор.

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  * `Executor`. Класс с методом `execute(Expr): Void` принимает `Expression`, то есть результат парсера. Он владеет `CommandStorage` и `IOEnvironment`. У каждой команды из `Expression` последовательн
А, вот что с аргументами :) Нет, хочется семантику как во всех остальных шеллах, аргументы и поток ввода --- разные вещи. Например, в bash `echo file.txt | cat` и `cat file.txt` ведут себя совсем по-разному.

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +  * `CommandStorage`. Хранилице наших команд, которые предстваляет из себя класс с полем storage: HashMap<String, Abstract Command> и методом getCommand(String): Abstract Command, который обращается
```suggestion
  * `CommandStorage`. Хранилице наших команд, которые предстваляет из себя класс с полем storage: HashMap<String, Abstract Command> и методом getCommand(String): Abstract Command, который обращается к storage. Ключи - названия всех команд, значения - соответствующие им классы
```
И, наверное, объекты? И --- а как они там оказываются?

2022-01-30 16:13 UTC, yurii-litvinov commented on hw01/README.md
> +    * `ExternalCommand`: вытаскиваем команду и аргументы из inputStream и исполняем внешнюю команду с помощью ProcessBuilder
Надо ещё по-хорошему выставлять наши текущие переменные окружения дочернему процессу

2022-02-03 13:25 UTC, Readrid commented on hw01/README.md
> +* `Lexer`. Представляет интерфейс обычного лексера с единственным методом `getNextToken()`. Конкретно в нашей реализации имеет имплементацию `LexerImpl`, которая разбивает текст на токены из `Token`.
Пофиксили в диаграмме направление стрелки

2022-02-03 13:27 UTC, Readrid commented
Избавились от Expression, потому что по сути это просто List<Command>. Также поправили замечания из review. 

@yurii-litvinov , можно проверять)

2022-02-03 17:20 UTC, yurii-litvinov requested changes
Почти. Осталось с аргументами/входным потоком разобраться (либо написать, что конкретно у вас будет так, потому-то и потому-то).

2022-02-03 17:20 UTC, yurii-litvinov commented on hw01/README.md
> +  Expression := (Command pipe Expression)* Command
Не, всё равно же странно получилось. Если хотите список команд, разделённых пайпами, то `Expression := Command (pipe Command)*`. Иначе это какая-то адски ветвящаяся и неоднозначная грамматика :)

2022-02-03 17:20 UTC, yurii-litvinov commented on hw01/README.md
> +  Треминалу Command соответствует класс `Command`, который содержит имя команды(String) и список аргументов(List<String>). Экземпляр класса `Command` строится в процесе парсинга одной команды. Для `A
```suggestion
  Терминалу Command соответствует класс `Command`, который содержит имя команды(String) и список аргументов(List<String>). Экземпляр класса `Command` строится в процессе парсинга одной команды. Для `AssigmentCommand` аргументами будут имя создаваемой переменной и её значение. 
```

2022-02-03 17:20 UTC, yurii-litvinov commented on hw01/README.md
> +* `Parser`. Интерфейс парсера. Стандартная имплементация(`ParserImpl`) принимает в конструкторе строку, которая в дальнешем парсится в методе `parse()`. `Parser` использует `Lexer`, постепенно получа
```suggestion
* `Parser`. Интерфейс парсера. Стандартная имплементация (`ParserImpl`) принимает в конструкторе строку, которая в дальнейшем парсится в методе `parse()`. `Parser` использует `Lexer`, постепенно получая из него новые токены, которые обрабатываются при помощи соответствующей грамматики. Попутно строится список `Command`, который возвращается в результате метода `parse()`.
```

2022-02-03 17:20 UTC, yurii-litvinov commented on hw01/README.md
> +  * `Executor`. Класс с методом `execute(Expr): Void` принимает `List<Command>`, то есть результат парсера. Он владеет `CommandStorage` и `IOEnvironment`. У каждой команды из `List<Command>` последов
С аргументами-то всё равно беда. Должны быть отдельно аргументы (то, что передаётся команде через командную строку, её параметры, они известны уже во время парсинга) и отдельно поток ввода (это данные, над которыми работает программа, он известен только в рантайме и не пуст только в пайпе). В приведённом мной примере `echo file.txt | cat` cat не имеет аргументов и во входном потоке у неё file.txt, поэтому она просто выводит "file.txt" на экран. `cat file.txt` не имеет входного потока и имеет один аргумент file.txt, поэтому печатает на экран его содержимое. Хочу, чтобы у вас так же было :)

2022-02-14 10:39 UTC, yurii-litvinov approved these changes
Судя по комментариям к коммитам вы через веб-интерфейс GitHub файлы выкладываете. Картинку в документации ладно (хотя за несодержательный комментарий минус, пока исключительно в карму). Но в общем случае это очень плохая идея.

В остальном почти всё ок, зачтена.

2022-02-14 10:39 UTC, yurii-litvinov commented on hw01/README.md
> +  * `Executor`. Класс с методом `execute(List<Command>): Void` принимает `List<Command>`, то есть результат парсера. Он владеет `IOEnvironment`. У каждой команды из `List<Command>` последовательно бу
Не понял, кто такой Result и влияет ли он как-то на исполнение пайпа (и работу шелла вообще, ведь Executor ничего не возвращает). Но с потоками теперь всё ок, так что ладно, не придираюсь.

2022-02-18 13:00 UTC, merged