HW03
usoltsev37/hse-homework-sd pull request #13
Opened 2022-02-11 20:17 UTC by Readrid

Выполнили:
[Владимир Федоров](@Readrid )
[Илья Смирнов](@smirok )
[Никита Усольцев](@usoltsev37 )

2022-02-14 13:15 UTC, yurii-litvinov requested changes
Ещё обработку ошибок надо улучшить, например, ошибку лексера/парсера как-то по-человечески показывать:
```
echo "
java.lang.IllegalStateException: Lexer Error: position 5
        at ru.hse.cli.parser.impl.LexerImpl.getNextToken(LexerImpl.kt:31)
        at ru.hse.cli.parser.impl.ParserImpl.accept(ParserImpl.kt:101)
        at ru.hse.cli.parser.impl.ParserImpl.parseAssignment(ParserImpl.kt:65)
        at ru.hse.cli.parser.impl.ParserImpl.parseCommand(ParserImpl.kt:39)
        at ru.hse.cli.parser.impl.ParserImpl.parse(ParserImpl.kt:26)
        at ru.hse.cli.MainKt.main(Main.kt:24)
        at ru.hse.cli.MainKt.main(Main.kt)
```

2022-02-14 13:15 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/CatCommand.kt
> +//            bodyWrite(body)
Во, тут правильно, но закомментировано :)

2022-02-14 13:15 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +            tempFile.writeText(inputArg)
Тут тоже теперь семантика правильная, но временный файл тут оверкилл и беспричинный удар по скорости работы

2022-02-14 13:15 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/parser/InputPreprocessor.kt
> +object InputPreprocessor {
Надо комментарии :)

2022-02-14 13:15 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/parser/InputPreprocessor.kt
> +            }
Переменные `b1`, `b2` и `c`, я таким кодом перваков пугаю. Переименуйте во что-нибудь с большей объясняющей способностью, пожалуйста.

2022-04-17 18:08 UTC, yurii-litvinov requested changes
В этой версии не работает пайп с cat-ом:
```
echo 123 | cat
java.io.ByteArrayInputStream@73a8dfcc
```
(как и cat без параметров)

И cat "README"'.md' не работает, думает, что ему два аргумента передали (тогда как настоящий bash сначала склеивает кавычки, а потом токенизирует). Это не критично, но если сможете поправить, будет круто.

И ещё конфликт при мёрдже. Поправьте, пожалуйста.

2022-04-17 18:08 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/exception/LexerException.kt
> +class LexerException(val name: String): Exception()
Вообще, им тоже надо комментарии

2022-05-16 10:56 UTC, yurii-litvinov commented
Напоминаю. cat не работает с пайпами, и конфликт с main-ом

2022-05-27 13:41 UTC, smirok commented
Я написал тест на `echo 123 | cat`. В CI все работает

2022-06-18 10:04 UTC, yurii-litvinov approved these changes
Ага, всё работает, кроме "настоящих" кавычек:
```
echo "1""23"
1
```
Зачтена

2022-06-22 19:51 UTC, merged