HW02
usoltsev37/hse-homework-sd pull request #9
Opened 2022-02-05 10:28 UTC by smirok

Выполнили:
[Илья Смирнов](@smirok) 
[Владимир Федоров](@Readrid)
[Никита Усольцев](@usoltsev37)

2022-02-05 12:06 UTC, usoltsev37 commented
Выполнили hw02 @yurii-litvinov

2022-02-05 16:20 UTC, yurii-litvinov requested changes
Внешние команды под Windows таки падают, причём с 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0                                                                                                        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1094)                                                                                                                                  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)                                                                                                                                  at ru.hse.cli.executor.commands.ExternalCommand.execute(ExternalCommand.kt:32)                                                                                                                         at ru.hse.cli.executor.Executor.execute(Executor.kt:18)                                                                                                                                                at ru.hse.cli.MainKt.main(Main.kt:26)                                         
```
Это я попробовал запустить команду `git`. На `git status` оно попыталось запустить команду status --- и тоже упало (хотя падать не должно даже при отсутствии команды)

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/build.gradle.kts
> +        attributes["Implementation-Title"] = "Bash CLI"
Он всё-таки не совсем Bash :)

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/CommandStorage.kt
> +object CommandStorage {
Вообще синглтоны лучше не использовать, потому что было бы удобно, например, в тестах свои заглушки для команд подложить, а синглтон это легко сделать не позволит. Но дело вкуса, можно не править.

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/CatCommand.kt
> +        }
Не, оно при отсутствии аргументов должно брать данные из входного потока и помещать их в выходной

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/EchoCommand.kt
> +            val arr: Array<String> = Array(args.size) { i -> args[i] }
![image](https://user-images.githubusercontent.com/706768/152647475-d5ba9f0c-679d-4619-8f51-e1568345333d.png)
Не сокращайте идентификаторы :)

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/ExternalCommand.kt
> +        processBuilder.redirectError(errorFile)
Можно было после исполнения сделать getInputStream()/getErrorStream(), всё равно же всё последовательно. Временные файлы создавать может быть излишне.

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +        for (arg in args) {
Как и cat, если аргументов нет, должна считать всё для входного потока. Вы старательно избегаете работы со входным потоком (и пока пайпов нет, он правда не нужен), но сделайте всё-таки :)

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +    }
Это вроде как не нужно

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/parser/Lexer.kt
> +interface Lexer {
Для самих интерфейсов тоже нужны комментарии (даже нужнее, чем для классов, ведь по принципу инверсии зависимостей все должны в основном как раз интерфейсами пользоваться)

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/parser/Parser.kt
> +    /** Parse given input and build [Command]
Что меня напрягает в этом интерфейсе — given input-то нет. Может, было бы логичнее передавать строку в parse(). Тем более что в архитектуре у вас так.

2022-02-05 16:20 UTC, yurii-litvinov commented on hw02/src/test/kotlin/ru/hse/cli/executor/commands/ExternalCommandTest.kt
> +    @DisabledOnOs(OS.WINDOWS)
Можно тестить на команде git. Она есть везде, где есть желание запускать вашу домашку, и одинакова под Windows и Linux.

2022-02-05 16:20 UTC, yurii-litvinov commented on README.md
> +-   `./gradlew.bat uberJar` for Windows
Кстати, винда умеет отбрасывать расширения исполнимых файлов сама, так что `./gradlew uberJar` под виндой тоже будет работать.

2022-02-05 16:20 UTC, yurii-litvinov commented on README.md
> +-   `./gradlew.bat test` for Windows
Была какая-то опция, которая добавляла отчёт по результатам тестов. Сейчас у вас (по крайней мере, у меня) оно просто говорит, что всё ок, таски исполнены. А надо --- сколько тестов запустилось, сколько прошло, сколько нет.

2022-02-11 13:34 UTC, Readrid commented on hw02/src/main/kotlin/ru/hse/cli/executor/CommandStorage.kt
> +object CommandStorage {
Решили не править

2022-02-11 13:39 UTC, Readrid commented on hw02/src/main/kotlin/ru/hse/cli/parser/Parser.kt
> +    /** Parse given input and build [Command]
В архитектуре у нас написано, что ParserImpl принимает именно в конструкторе input как строку, однако на самой диаграмме классов в интерфейсе и правда забыли убрать лишний аргумент у parse. Добавлять аргумент в parse не хочется пока, так как там ломается вся имплементация и приходится делать очень некрасиво(например, либо передавать во все функции лексер либо давать возможным делать его Null, либо в лексере тоже что-то менять).

2022-02-14 12:34 UTC, yurii-litvinov requested changes
```
cat
Error:
File 'java.io.ByteArrayInputStream@36f6e879' does not exist!
```
```
wc
1 1 37
```
Это вроде один баг, и я про него  в реализации ещё откомментил, но забавно (и видно, что не тестировали :angry:)

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/README.md
> +-   `./gradlew uberJar` for Windows
```suggestion
`./gradlew uberJar` 
```

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/README.md
> +-   `./gradlew test` for Windows
```suggestion
`./gradlew test`
```

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/exception/UnknownCommandException.kt
> +class UnknownCommandException(val name: String): Exception()
Исключениям тоже нужны комментарии по-хорошему

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/CatCommand.kt
> +            val files = ioEnvironment.inputStream.toString().split(" ")
Не-а. cat в случае отсутствия аргументов не берёт из входного потока имена файлов, она считает входной поток файлом (то есть просто выдаёт всё, что ей пришло). Попробуйте с реальным cat.

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +            }
Омг. Нет :) То же, что и в cat, но тут ещё и неконсистентная семантика, зависящая от случайного наличия файла в файловой системе. Одна хорошая IDE-шка, помнится, вела себя _очень_ _странно_, если на диске был файл out, а ей надо было папку out создать, не повторяйте чужих ошибок.

2022-02-14 12:34 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/parser/Parser.kt
> +    /** Parse given input and build [Command]
Хорошо, давайте так оставим, но вообще передавать во все функции лексер может быть хорошей идеей — взамен вы получаете возможность вообще убрать состояние у ParserImpl и побочные эффекты у функций-продукций.

Но возможно, я необъективен, поскольку люблю функциональное программирование — я б завёл какую-нибудь структуру ParserState и таскал бы её везде.

2022-02-18 11:54 UTC, usoltsev37 commented
@yurii-litvinov выполнили исправления HW02

2022-02-23 11:51 UTC, yurii-litvinov requested changes
Что-то вы поторопились. Теперь в обычном случае cat работает как надо, но если без параметров, радостно печатает `java.io.ByteArrayInputStream@73a28541`. И код сыроват. Доисправляйте, пожалуйста, уже совсем чуть-чуть осталось

2022-02-23 11:51 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/CatCommand.kt
> +    /**
```suggestion
    }
    
    /**
```

2022-02-23 11:51 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +//        return result
Ой. Закомментированный код не нужен

2022-02-23 11:51 UTC, yurii-litvinov commented on hw02/src/main/kotlin/ru/hse/cli/executor/commands/WcCommand.kt
> +                max(0, cntLines - 1) // file.length().toInt()
И тут

2022-04-17 17:59 UTC, yurii-litvinov approved these changes
👍

2022-04-25 19:18 UTC, merged